# $Id: Makefile,v 1.1 2004/07/12 12:59:45 alexkhansen Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = saos-pages.xml
TARGET = index.php essential.php window-manager.php fink-and-panther.php
WANT_HTML = 1
DESTDIR = doc/saos-pages

LANGUAGES = en
include $(basedir)/Makefile.i18n.common

# eof
