# $Id: Makefile,v 1.2 2004/07/17 17:28:54 sao_x Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = saos-pages.xml
#TARGET = index.php essential.php window-manager.php fink-and-panther.php
TARGET = index.php essential.php finkandpanther.php finkandpanther2.php finkcommander.php commands.php faqs.php faqs2.php faqs3.php faqs10.php help.php how.php install.php tips.php utils.php wmanagers.php
WANT_HTML = 1
DESTDIR = doc/saos-pages

LANGUAGES = en
include $(basedir)/Makefile.i18n.common

# eof
