<?
/* $Id: header.inc,v 1.7 2001/10/25 10:11:39 chrisp Exp $ */

$section = "faq";
$navbox = array(
  "faq/index.php", "FAQ Contents",
  "faq/general.php", "General",
  "faq/relations.php", "Relations",
  "faq/usage-fink.php", "Distribution",
  "faq/comp-general.php", "Compiling (1)",
  "faq/comp-packages.php", "Compiling (2)",
  "faq/usage-general.php", "Usage (1)",
  "faq/usage-packages.php", "Usage (2)"
);

$fsroot = $root = "../";
include $fsroot."header.inc";
?>
