<?
/* $Id: header.inc,v 1.8 2001/11/04 21:24:41 chrisp Exp $ */

$section = "faq";
$navbox = array(
  "faq/index.php", "FAQ Contents",
  "faq/general.php", "General",
  "faq/relations.php", "Relations",
  "faq/usage-fink.php", "Distribution",
  "faq/comp-general.php", "Compiling (1)",
  "faq/comp-packages.php", "Compiling (2)",
  "faq/usage-general.php", "Usage (1)",
  "faq/usage-packages.php", "Usage (2)"
);
$printlink = "faq/faq.html";

$fsroot = $root = "../";
include $fsroot."header.inc";
?>
