<?
/* $Id: header.inc,v 1.7 2002/05/15 19:28:51 dmrrsn Exp $ */

$section = "documentation";
$parents = array("doc/index.php", "Document List");
$navbox = array(
  "doc/porting/index.php", "Contents",
  "doc/porting/basics.php", "Basics",
  "doc/porting/shared.php", "Shared Code",
  "doc/porting/libtool.php", "Libtool",
  "doc/porting/preparing.php", "10.2"
);
$printlink = "doc/porting/porting.html";

$fsroot = $root = "../../";
include $fsroot."header.inc";
?>
