<?
/* $Id: header.inc,v 1.4 2001/09/30 14:57:24 chrisp Exp $ */

$section = "documentation";
$parents = array("doc/index.php", "Document List");
$navbox = array(
  "doc/users-guide/index.php", "Contents",
  "doc/users-guide/intro.php", "Introduction",
  "doc/users-guide/install.php", "First Install",
  "doc/users-guide/packages.php", "Packages",
  "doc/users-guide/upgrade.php", "Upgrade"
);

$fsroot = $root = "../../";
include $fsroot."header.inc";
?>
