# $Id: Makefile,v 1.7 2005/01/16 09:41:52 horsager Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = doc.xml
TARGET = index.php 
WANT_HTML = 1
DESTDIR = doc

LANGUAGES_AVAILABLE = fr en ja zh es ru
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.i18n.common

# eof
