# $Id: Makefile,v 1.2 2004/02/28 16:18:39 babayoshihiko Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = doc.xml
TARGET = index.php 
WANT_HTML = 1
DESTDIR = doc

LANGUAGES = en ja
include $(basedir)/Makefile.i18n.common

# eof
