# $Id: Makefile,v 1.6 2004/10/20 11:11:22 dmacks Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = doc.xml
TARGET = index.php 
WANT_HTML = 1
DESTDIR = doc

LANGUAGES_AVAILABLE = fr en ja zh es
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.i18n.common

# eof
