<?
/* $Id: nav.pt.inc,v 1.2 2009/04/01 02:32:30 monipol Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=pt", "Lista de documentos",
  "doc/users-guide/index.php?phpLang=pt", "Guia do usuário",
  "doc/advanced/index.php?phpLang=pt", "Avançado",
  "doc/x11/index.php?phpLang=pt", "Rodando X11",
  "doc/bundled/install.php?phpLang=en", "Installation",
  "doc/bundled/usage.php?phpLang=en", "Usage",
  "doc/readme.php?phpLang=pt", "LeiaMe",
  "doc/cvsaccess/index.php?phpLang=pt", "Acesso via CVS",
  "doc/security/index.php?phpLang=pt", "Segurança",
  "doc/porting/index.php?phpLang=en", "Porting",
  "doc/quick-start-pkg/index.php?phpLang=en", "Packaging Tutorial",
  "doc/packaging/index.php?phpLang=en", "Packaging Manual",
  "doc/multilingual/index.php?phpLang=en", "Internationalization",
  "doc/netiquette/index.php?phpLang=en", "Netiquette"
);

?>
