<?php
/* $Id: constants.pt.inc,v 1.5 2014/10/23 22:09:49 thesin Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://www.finkproject.org)                           |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will not show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_LC_ALL", 'pt_BR');

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME", 'Página inicial');
define ("FINK_SECTION_DOWNLOAD", 'Download');
define ("FINK_SECTION_PACKAGE", 'Pacotes');
define ("FINK_SECTION_HELP", 'Ajuda');
define ("FINK_SECTION_FAQ", 'Perguntas frequentes');
define ("FINK_SECTION_DOCUMENTATION", 'Documentação');
define ("FINK_SECTION_MAILING_LISTS", 'Listas de discussão');

/* The Home Subsections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME_INDEX", 'Índice');
define ("FINK_SECTION_HOME_NEWS", 'Notícias');
define ("FINK_SECTION_HOME_ABOUT", 'Sobre o Fink');
define ("FINK_SECTION_HOME_CONTRIBUTORS", 'Colaboradores');
define ("FINK_SECTION_HOME_LINKS", 'Links');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define ("FINK_SECTIONS", 'Seções');

/* Used in FAQ/Documentation Sections */
define ("FINK_CONTENTS", 'Sumário');
define ("FINK_NEXT", 'Próximo');
define ("FINK_Q", 'P.');
define ("FINK_A", 'R.');

/* Printer */
define ("FINK_PRINTER", 'Imprimir');
define ("FINK_PRINT_VERSION", 'Versão para impressão');

/* Footer */
define ("META_KEYWORDS", 'Mac OS X, Fink, Debian, Macintosh, Apple, UNIX, Open Source, download, código aberto, ports, desenvolvimento, gerenciamento de pacotes');
define ("META_DESCRIPTION", 'O projeto Fink deseja trazer ao Darwin e ao Mac OS X todo o mundo de software Unix de código aberto. Nós modificamos softwares originalmente desenvolvidos para Unix tal que eles sejam compilados e executados no Mac OS X, e os disponibilizamos para download como uma distribuição coesa');
//define ("HEADER_HOSTED_BY", 'Hospedado por {img}');
define ("FOOTER_AVAILABLE_LANGUAGES", 'Idiomas disponíveis ');
define ("FOOTER_GENERATED_DYNAMICALLY", 'Generado dinamicamente por ');
define ("FOOTER_DATABASE_LAST_UPDATED", 'Última atualização em %d %B %Y às %R %Z');
define ("FOOTER_LAST_CHANGED", 'Última atualização em {date} às {time} por {author}');
?>
