<?php
/* $Id: constants.de.inc,v 1.11 2014/10/23 22:09:49 thesin Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://www.finkproject.org)                           |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will not show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_LC_ALL", 'de_DE');

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME", 'Home');
define ("FINK_SECTION_DOWNLOAD", 'Download');
define ("FINK_SECTION_PACKAGE", 'Pakete');
define ("FINK_SECTION_HELP", 'Hilfe');
define ("FINK_SECTION_FAQ", 'F.A.Q.');
define ("FINK_SECTION_DOCUMENTATION", 'Dokumentation');
define ("FINK_SECTION_MAILING_LISTS", 'Mailing Listen');

/* The Home Subsections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME_INDEX", 'Index');
define ("FINK_SECTION_HOME_NEWS", 'Neuigkeiten');
define ("FINK_SECTION_HOME_ABOUT", 'Über Fink');
define ("FINK_SECTION_HOME_CONTRIBUTORS", 'Mitwirkende');
define ("FINK_SECTION_HOME_LINKS", 'Links');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define ("FINK_SECTIONS", 'Kapitel');

/* Used in FAQ/Documentation Sections */
define ("FINK_CONTENTS", 'Inhalt');
define ("FINK_NEXT", 'Weiter');
define ("FINK_Q", 'F.');
define ("FINK_A", 'A.');

/* Printer */
define ("FINK_PRINTER", 'Drucker');
define ("FINK_PRINT_VERSION", 'Druckreife Version');

/* Footer */
define ("META_KEYWORDS", 'Mac OS X, Fink, Debian, Macintosh, Apple, UNIX, Open Source, Download, free software, porting, development, package management');
define ("META_DESCRIPTION", "Fink hat es sich zur Aufgabe gemacht, die ganze Welt der Unix Open Source Software auf Darwin und Mac OS X zu bringen. Wir modifizieren Unix Software, so dass Sie unter Mac OS X compiliert bzw. ausgeführt werden kann, und machen die Ergebnisse dem Gelegenheitsnutzern zugänglich als eine zusammenhängende, komfortable Distribution.");
//define ("HEADER_HOSTED_BY", 'Beherbergt von {img}');
define ("FOOTER_AVAILABLE_LANGUAGES", 'Verfügbare Sprachen ');
define ("FOOTER_GENERATED_DYNAMICALLY", 'Erzeugt aus ');
define ("FOOTER_DATABASE_LAST_UPDATED", 'Letzte Änderung durch %d %B %Y bei %R %Z');
define ("FOOTER_LAST_CHANGED", 'Letzte Änderung am {date}, {time} durch {author}');
?>
