<?
/* $Id: constants.zh.inc,v 1.10 2010/09/05 10:56:04 gecko2 Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://www.finkproject.org)                           |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will not show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_LC_ALL", 'zh_CN');
define ("FINK_SF_ENCODING", 'UTF-8');
define ("FINK_DATE_FORMAT", '%Y年%m月%e日');

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME", '首页');
define ("FINK_SECTION_DOWNLOAD", '下载');
define ("FINK_SECTION_PACKAGE", '软件包');
define ("FINK_SECTION_HELP", '帮助');
define ("FINK_SECTION_FAQ", '常见疑问');
define ("FINK_SECTION_DOCUMENTATION", '文档');
define ("FINK_SECTION_MAILING_LISTS", '邮件列表');

/* The Home Subsections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME_INDEX", '索引');
define ("FINK_SECTION_HOME_NEWS", '新闻');
define ("FINK_SECTION_HOME_ABOUT", '关于 Fink');
define ("FINK_SECTION_HOME_CONTRIBUTORS", '贡献者');
define ("FINK_SECTION_HOME_LINKS", '链接');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define ("FINK_SECTIONS", '分类');

/* Contents as Table of Contents.  Used in FAQ/Documentation Sections */
define ("FINK_CONTENTS", '目录');

/* Printer */
define ("FINK_PRINTER", '打印机');
define ("FINK_PRINT_VERSION", '打印版本');

/* Footer */
define ("META_KEYWORDS", 'Mac OS X, Fink, Debian, 麦金塔, 苹果, UNIX, 开放源码,
             下载, 自由软件, 移植, 开发, 软件包管理');
define ("META_DESCRIPTION", 'Fink 项目希望把 Unix              世界的各种自由软件带到 Darwin 和 Mac OS X 平台上。我们修改 Unix 软件，使得它们可以在 Mac OS X 上编译和运行，并使得它们作为一个整体的发行版本来被下载。');
define ("HEADER_HOSTED_BY", '网页寄存于 {img}');
define ("FOOTER_AVAILABLE_LANGUAGES", '现有语言版本');
define ("FOOTER_GENERATED_DYNAMICALLY", '动态创建自');
define ("FOOTER_DATABASE_LAST_UPDATED", '最后更新：%x %X');
define ("FOOTER_LAST_CHANGED", '最后修改者 {author}，于 {date}, {time}');
?>
