<?
/* $Id: constants.ja.inc,v 1.2 2004/03/01 23:19:34 babayoshihiko Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://fink.sourceforge.net)                          |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will now show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME, 'ホーム');
define (FINK_SECTION_DOWNLOAD, 'ダウンロード');
define (FINK_SECTION_PACKAGE, 'パッケージ');
define (FINK_SECTION_HELP, 'ヘルプ');
define (FINK_SECTION_FAQ, 'F.A.Q.');
define (FINK_SECTION_DOCUMENTATION, '文書');
define (FINK_SECTION_MAILING_LISTS, 'メーリングリスト');

/* The Home Subsections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME_INDEX, 'ホーム');
define (FINK_SECTION_HOME_NEWS, 'ニュース');
define (FINK_SECTION_HOME_ABOUT, 'Fink について');
define (FINK_SECTION_HOME_CONTRIBUTORS, '人々');
define (FINK_SECTION_HOME_LINKS, 'リンク');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define (FINK_SECTIONS, 'セクション');

/* Contents as Table of Contents.  Used in FAQ/Documentation Sections */
define (FINK_CONTENTS, '目次');
?>