<?
/* $Id: constants.ru.inc,v 1.3 2005/01/16 17:28:44 babayoshihiko Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://fink.sourceforge.net)                          |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will not show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define (FINK_LC_ALL, 'ru_RU');
define (FINK_SF_ENCODING, 'ISO-8859-5');

/* The Sections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME, 'Главная');
define (FINK_SECTION_DOWNLOAD, 'Скачивание');
define (FINK_SECTION_PACKAGE, 'Пакеты');
define (FINK_SECTION_HELP, 'Помощь');
define (FINK_SECTION_FAQ, 'Ч.З.В.');
define (FINK_SECTION_DOCUMENTATION, 'Документация');
define (FINK_SECTION_MAILING_LISTS, 'Списки рассылки');

/* The Home Subsections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME_INDEX, 'Указатель');
define (FINK_SECTION_HOME_NEWS, 'Последние новости');
define (FINK_SECTION_HOME_ABOUT, 'О нас');
define (FINK_SECTION_HOME_CONTRIBUTORS, 'Участники');
define (FINK_SECTION_HOME_LINKS, 'Ссылки');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define (FINK_SECTIONS, 'Разделы');

/* Used in FAQ/Documentation Sections */
define (FINK_CONTENTS, 'Содержание');
define (FINK_NEXT, 'Следующий');
define (FINK_Q, 'В');
define (FINK_A, 'О');

/* Printer */
define (FINK_PRINTER, 'Принтер');
define (FINK_PRINT_VERSION, 'Печатная версия');

/* Footer */
define (META_KEYWORDS, 'Mac OS X, Fink, Debian, Macintosh, Apple, UNIX, Open Source, скачивание, свободное программное обеспечение, порт, разработка, управлением пакетами');
define (META_DESCRIPTION, 'Проект Fink нацелен на перенос всего мира ПО Unix с открытым исходным кодом в Darwin и Mac OS X. Мы модифицируем ПО Unix таким образом, чтобы оно могло компилироваться и использоваться в Mac OS X (переносим его), и обеспечиваем возможность его скачивания в виде связной дистрибуции. ');
define (HEADER_HOSTED_BY, 'Хостинг обеспечен');
define (FOOTER_AVAILABLE_LANGUAGES, 'Языки');
define (FOOTER_GENERATED_DYNAMICALLY, 'Воспроизведено динамически ');
define (FOOTER_DATABASE_LAST_UPDATED, 'Последнее обновление: %a, %d %B %Y ‚ %R %Z');
define (FOOTER_LAST_CHANGED, 'Последнее изменение: {author} %a, %d %B %Y ‚ %R %Z ');
?>

