<?
/* $Id: constants.es.inc,v 1.5 2010/09/05 10:56:04 gecko2 Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://www.finkproject.org)                           |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will not show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_LC_ALL", 'es_ES');

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME", 'Home');
define ("FINK_SECTION_DOWNLOAD", 'Descargas');
define ("FINK_SECTION_PACKAGE", 'Paquetes');
define ("FINK_SECTION_HELP", 'Ayuda');
define ("FINK_SECTION_FAQ", 'F.A.Q.');
define ("FINK_SECTION_DOCUMENTATION", 'Documentación');
define ("FINK_SECTION_MAILING_LISTS", 'Listas de correo');

/* The Home Subsections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME_INDEX", 'Indice');
define ("FINK_SECTION_HOME_NEWS", 'Noticias');
define ("FINK_SECTION_HOME_ABOUT", 'Acerca de Fink');
define ("FINK_SECTION_HOME_CONTRIBUTORS", 'Contribuyentes');
define ("FINK_SECTION_HOME_LINKS", 'Vínculos');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define ("FINK_SECTIONS", 'Secciones');

/* Used in FAQ/Documentation Sections */
define ("FINK_CONTENTS", 'Contenido');
define ("FINK_NEXT", 'Siguiente');
define ("FINK_Q", 'P.');
define ("FINK_A", 'R.');

/* Printer */
define ("FINK_PRINTER", 'Imprimir');
define ("FINK_PRINT_VERSION", 'Versión imprimible');

/* Footer */
define ("META_KEYWORDS", 'Mac OS X, Fink, Debian, Macintosh, Apple, UNIX, Open Source, descargas, código abierto, puertos, desarrollo, gestión de paquetes');
define ("META_DESCRIPTION", 'Fink es un proyecto que desea traer todo el mundo del software Unix de Open Source a Darwin y a Mac OS X. Modificamos el software existente de Códifo Abierto (Open Source)
de tal manera que pueda compilarse y ejecutarse en Mac OS X y hacemos el resultado del primer objetivo disponible al usuario
casual de manera coherente y comoda en una distribución que se asemeje a lo que el usuario de
Linux esta acostumbrado.');


define ("HEADER_HOSTED_BY", 'Albergado por {img}');
define ("FOOTER_AVAILABLE_LANGUAGES", 'Idiomas disponibles ');
define ("FOOTER_GENERATED_DYNAMICALLY", 'Generado dinámicamente por ');
define ("FOOTER_DATABASE_LAST_UPDATED", 'Actualizado por última vez el %d %B %Y a la(s) %R %Z');
define ("FOOTER_LAST_CHANGED", 'Actualizado por última vez el {date} a la(s) {time} por {author}');
?>
