<?
/* $Id: constants.fr.inc,v 1.2 2004/03/10 23:03:24 fingolfin Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://fink.sourceforge.net)                          |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will now show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME, 'Accueil');
define (FINK_SECTION_DOWNLOAD, 'Téléchargements');
define (FINK_SECTION_PACKAGE, 'Paquets');
define (FINK_SECTION_HELP, 'Aide');
define (FINK_SECTION_FAQ, 'Q.F.P.');
define (FINK_SECTION_DOCUMENTATION, 'Documentation');
define (FINK_SECTION_MAILING_LISTS, 'Listes de diffusion');

/* The Home Subsections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME_INDEX, 'Index');
define (FINK_SECTION_HOME_NEWS, 'Dernières nouvelles');
define (FINK_SECTION_HOME_ABOUT, 'À propos de Fink');
define (FINK_SECTION_HOME_CONTRIBUTORS, 'Contributeurs');
define (FINK_SECTION_HOME_LINKS, 'Liens');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define (FINK_SECTIONS, 'Sections');

/* Contents as Table of Contents.  Used in FAQ/Documentation Sections */
define (FINK_CONTENTS, 'Sommaire');
?>