<?php
/* $Id: constants.fr.inc,v 1.13 2014/10/23 22:09:49 thesin Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://www.finkproject.org)                           |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will not show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_LC_ALL", 'fr_FR');

/* The Sections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME", 'Accueil');
define ("FINK_SECTION_DOWNLOAD", 'Téléchargements');
define ("FINK_SECTION_PACKAGE", 'Paquets');
define ("FINK_SECTION_HELP", 'Aide');
define ("FINK_SECTION_FAQ", 'Q.F.P.');
define ("FINK_SECTION_DOCUMENTATION", 'Documentation');
define ("FINK_SECTION_MAILING_LISTS", 'Listes de diffusion');

/* The Home Subsections.  Used in Menu Navigation Bar */
define ("FINK_SECTION_HOME_INDEX", 'Index');
define ("FINK_SECTION_HOME_NEWS", 'Dernières nouvelles');
define ("FINK_SECTION_HOME_ABOUT", 'À propos de Fink');
define ("FINK_SECTION_HOME_CONTRIBUTORS", 'Contributeurs');
define ("FINK_SECTION_HOME_LINKS", 'Liens');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define ("FINK_SECTIONS", 'Sections');

/* Used in FAQ/Documentation Sections */
define ("FINK_CONTENTS", 'Sommaire');
define ("FINK_NEXT", 'Suite');
define ("FINK_Q", 'Q.');
define ("FINK_A", 'R.');

/* Printer */
define ("FINK_PRINTER", 'Imprimante');
define ("FINK_PRINT_VERSION", 'Version imprimable');

/* Footer */
define ("META_KEYWORDS", 'Mac OS X, Fink, Debian, Macintosh, Apple, UNIX, Open Source, téléchargement, logiciels libres, portage, développement, gestion de paquets');
define ("META_DESCRIPTION", "Le projet Fink a pour but d'ouvrir toutes grandes les portes du monde des logiciels Open Source Unix à Darwin et à Mac OS X. Nous modifions les logiciels Unix pour qu'ils compilent et tournent sur Mac OS X et en faisons une distribution cohérente téléchargeable.");
//define ("HEADER_HOSTED_BY", 'Hébergé par {img}');
define ("FOOTER_AVAILABLE_LANGUAGES", 'Langues disponibles ');
define ("FOOTER_GENERATED_DYNAMICALLY", 'Généré dynamiquement par ');
define ("FOOTER_DATABASE_LAST_UPDATED", 'Dernière mise à jour le %d %B %Y à %R %Z');
define ("FOOTER_LAST_CHANGED", 'Dernière mise à jour le {date} à {time} par {author}');
?>
