<?
/* $Id: constants.zh.inc,v 1.2 2004/03/10 23:03:24 fingolfin Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://fink.sourceforge.net)                          |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will now show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME, '首页');
define (FINK_SECTION_DOWNLOAD, '下载');
define (FINK_SECTION_PACKAGE, '软件包');
define (FINK_SECTION_HELP, '帮助');
define (FINK_SECTION_FAQ, '常见疑问');
define (FINK_SECTION_DOCUMENTATION, '文档');
define (FINK_SECTION_MAILING_LISTS, '邮件列表');

/* The Home Subsections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME_INDEX, '索引');
define (FINK_SECTION_HOME_NEWS, '新闻');
define (FINK_SECTION_HOME_ABOUT, '关于 Fink');
define (FINK_SECTION_HOME_CONTRIBUTORS, '贡献者');
define (FINK_SECTION_HOME_LINKS, '链接');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define (FINK_SECTIONS, '分类');

/* Contents as Table of Contents.  Used in FAQ/Documentation Sections */
define (FINK_CONTENTS, '目录');
?>