<?
/* $Id: constants.zh.inc,v 1.5 2005/01/17 00:58:23 babayoshihiko Exp $ */
// +--------------------------------------------------------------------------+
// | Constants                                                                |
// +--------------------------------------------------------------------------+
// | Copyright (c)                                                            |
// +--------------------------------------------------------------------------+
// | License:  GNU/GPL - http://www.gnu.org/copyleft/gpl.html                 |
// +--------------------------------------------------------------------------+
// | Defines the constants used throughout the Fink website                   |
// | for different human languages                                            |
// |                   (http://fink.sourceforge.net)                          |
// |                                                                          |
// | usage:    1. read the comments                                           |
// |           2. encoding must be UTF-8 or it will not show properly         |
// +--------------------------------------------------------------------------+

/* The Sections.  Used in Menu Navigation Bar */
define (FINK_LC_ALL, 'zh_CN');
define (FINK_SF_ENCODING, 'gb2312');
define (FINK_DATE_FORMAT, '%YÇ¯%m·î%eÆü');

/* The Sections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME, 'é¦{íáT');
define (FINK_SECTION_DOWNLOAD, 'ä¸v¯ï\');
define (FINK_SECTION_PACKAGE, 'è½¯ä»¶åŒsF);
define (FINK_SECTION_HELP, 'å¸®åuŽ§');
define (FINK_SECTION_FAQ, 'å¸¸è§ç–y±ÝM');
define (FINK_SECTION_DOCUMENTATION, 'åôt«áB');
define (FINK_SECTION_MAILING_LISTS, 'é‚®ä»¶åˆ|¯áG');

/* The Home Subsections.  Used in Menu Navigation Bar */
define (FINK_SECTION_HOME_INDEX, 'ç´¢å»ó');
define (FINK_SECTION_HOME_NEWS, 'åô°é|Z');
define (FINK_SECTION_HOME_ABOUT, 'å…³ä¹ì Fink');
define (FINK_SECTION_HOME_CONTRIBUTORS, 'è´¡çvŽ¬çßsF);
define (FINK_SECTION_HOME_LINKS, 'é“¾æŽ¥');

/* The word 'Sections'.  Used in Menu Navigation Bar */
define (FINK_SECTIONS, 'åˆsééZ');

/* Contents as Table of Contents.  Used in FAQ/Documentation Sections */
define (FINK_CONTENTS, 'ç›®å½•');

/* Printer */
define (FINK_PRINTER, 'åçz©ØOåúº§);
define (FINK_PRINT_VERSION, 'åçz©ØOç‰tçßŽª');

/* Footer */
define (META_KEYWORDS, 'Mac OS X, Fink, Debian, éº¦ét0å¡zŽª çé¹æÓ UNIX, å¼pçÛŽ¼æºxéà,
             ä¸v¯ï\, çåªçzŽ¯è½¯ä»¶, ç§»æ£ë, å¼påÙ0, è½¯ä»¶åŒs­çÞæ/sŽ¥);
define (META_DESCRIPTION, 'Fink é¡¹ç~Må¸vçßÒå¯ÖÛ¶nix              ä¸{éÜ+çšråÙ¤æFw¯ÕIç”±è½¯ä»¶å¸¦åˆ¯þDarwin å’vÛ®ac OS X å¹³åxOä¸uáÑŽ€åæy§îKä¿®æzŽ· Unix è½¯ä»¶ï¼vãï^å¾|©ç¢äŽ¹¬åxNä»¥å~Ž¦ Mac OS X ä¸uéîÈæŽ­y©Ú´æŽ½xëá+ï¼våíUä½¿å½õå®r§îKä½~ãìŽ¸ä¸pãìŽ¨åó´ä½“çšråÙ0è¡véÖ'åú¬æDè¢«ä·éè½½ãpŽ€');
define (HEADER_HOSTED_BY, 'ç½y±áTå¯råç7äº {img}');
define (FOOTER_AVAILABLE_LANGUAGES, 'çŽ°æ~®æŽ­­è§ßç‰tçßŽª');
define (FOOTER_GENERATED_DYNAMICALLY, 'åŠ¨æpåˆ~©îYçåª§);
define (FOOTER_DATABASE_LAST_UPDATED, 'åúpåÙ¸åÑêçÜŽ®ï¼}Ž£x %X');
define (FOOTER_LAST_CHANGED, 'åúpåÙ¸äŽ½®æzŽ·çßs?{author}ï¼vãí·%a, %d %b %Y,  %R %Z');
?>
