<?
/* $Id: footer.inc,v 1.1 2001/01/07 23:14:15 chrisp Exp $ */
?>

</td></tr>
<tr><td>&nbsp;</td></tr>
</table>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr valign="bottom"><td>&nbsp;&nbsp;&nbsp;</td>
<td align="right">

<p><font size="-1">Last changed <?
print strftime("%a, %b %d %Y", $date);
?></font></p>

</td>
<td>&nbsp;&nbsp;&nbsp;</td></tr>

<tr><td colspan="3" background="img/bottom-line.gif"><img
src="img/bottom-line.gif" width="32" height="8" border="0"
alt="-----"></td></tr>

<tr valign="top"><td></td><td>

<p><font size="-1">Copyright (c) 2000,2001
Christoph Pfisterer. This site in neither approved nor endorsed by
Apple Inc. All trademarks are the property of their respective
holders.</font></p>

</td>
<td>&nbsp;&nbsp;&nbsp;</td></tr>
</table>

</body>
</html>
