# $Id: Makefile,v 1.4 2001/09/16 18:48:37 chrisp Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = faq.xml
TARGET = index.php general.php relations.php \
	 install.php usage.php packages.php
DESTDIR = faq

include $(basedir)/Makefile.common

# eof
