# $Id: Makefile,v 1.14 2005/06/23 20:16:35 dmrrsn Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = packaging.xml
TARGET = index.php intro.php format.php policy.php fslayout.php compilers.php reference.php
WANT_HTML = 1
DESTDIR = doc/packaging

LANGUAGES_AVAILABLE = en fr zh ja
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.i18n.common

# eof
