# $Id: Makefile,v 1.11 2004/03/19 17:50:02 michga Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = packaging.xml
TARGET = index.php intro.php format.php policy.php fslayout.php reference.php
WANT_HTML = 1
DESTDIR = doc/packaging

LANGUAGES = en fr zh
include $(basedir)/Makefile.i18n.common

# eof
