# $Id: Makefile,v 1.2 2001/06/28 10:21:18 chrisp Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = packaging.xml
TARGET = info-format.php

include $(basedir)/Makefile.common

# eof
