# $Id: Makefile,v 1.7 2004/03/16 04:03:28 jeff_yecn Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = cvs.xml
TARGET = index.php
WANT_HTML = 1
DESTDIR = doc/cvsaccess

LANGUAGES = fr en zh
include $(basedir)/Makefile.i18n.common

# eof
