# $Id: Makefile,v 1.10 2005/01/16 09:43:33 horsager Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = cvs.xml
TARGET = index.php
WANT_HTML = 1
DESTDIR = doc/cvsaccess

LANGUAGES_AVAILABLE = fr en zh es ru
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.i18n.common

# eof
