# $Id: Makefile,v 1.15 2015/02/19 15:21:03 k-m_schindler Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = cvs
TARGET = index.php
WANT_HTML = 1
DESTDIR = doc/cvsaccess

LANGUAGES_AVAILABLE = en de es fr ja ru pt zh
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.common

# eof
