<a name="2014-11-29%20fink-0.38.0%20released."><span class="news-date">2014-11-29: </span><span class="news-headline">fink-0.38.0 released.</span></a><?php gray_line(); ?>
  <p>
  <code>fink-0.38.3</code> was released on 29 November, 2014.  This release enables the
  official 10.10 binary distribution by default, along with official OS X 10.10.1 support
  and other fixes and enhancements.
  </p>
  <a name="2014-10-18%20Yosemite%20support:%20fink-0.38.0%20%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9"><span class="news-date">2014-10-18: </span><span class="news-headline">Yosemite support: fink-0.38.0 リリース</span></a><?php gray_line(); ?>
  <p>
  <code>fink-0.38.0</code> が、2014年10月18日にリリースされました。
  Fink Project は、<code>fink-0.38.0</code> のリリースにともない、
  Yosemite (OS X 10.10) の公式サポートをお知らせいたします。
  </p>
  <p>
  10.9 ユーザで、10.9 から 10.10 へ Fink をアップグレードしたい場合は、
  10.9 上で、 10.10 に更新する前に  <code>fink-0.38.0</code> (またはそれ以降) をインストールしなければなりません。
  10.8 以前からの 10.10 へのアップグレードは対応していません。
  </p>
 <a name="2014-9-20%20fink-0.37.1%20%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9"><span class="news-date">2014-9-20: </span><span class="news-headline">fink-0.37.1 リリース</span></a><?php gray_line(); ?>
  <p>
  <code>fink-0.37.1</code> が、2014年11月20日にリリースされました。
  このリリースでは、10.9 上で Xcode 6.x を使った bootstrap をはじめとして、
  いくつかの修正を行いました。
  さらに、10.9.4 と 10.9.5 に公式に対応しました。
  </p>
 
