<a name="2013-03-29%20fink-0.34.7%20released"><span class="news-date">2013-03-29: </span><span class="news-headline">fink-0.34.7 released</span></a><?php gray_line(); ?>
  <p><code>fink-0.34.7</code> was released on 29 March, 2013.  This release addresses
  an issue in which <code>tar</code> hangs for certain root access methods.</p>
 <a name="2013-03-16%20fink-0.34.6%20released"><span class="news-date">2013-03-16: </span><span class="news-headline">fink-0.34.6 released</span></a><?php gray_line(); ?>
  <p><code>fink-0.34.6</code> was released on 16 March, 2013.  This release supports
  OS 10.8.3.</p>
 <a name="2013-01-28%20fink-0.34.5%20released"><span class="news-date">2013-01-28: </span><span class="news-headline">fink-0.34.5 released</span></a><?php gray_line(); ?>
  <p><code>fink-0.34.5</code> was released on 28 January, 2013.  In addition to some
  other improvements, this release addresses an issue with detecting the version of
  the <code>clang</code> compiler from Xcode 4.6 and later.</p>
 
