# $Id: Makefile,v 1.7 2002/06/08 00:57:26 dmrrsn Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = install.xml
TARGET = install.php install-fast.php install-first.php \
	 install-up03.php install-up02.php install-up01.php
WANT_HTML = 1
DESTDIR = doc/bundled

include $(basedir)/Makefile.common

# eof
