# $Id: Makefile,v 1.3 2001/07/25 18:53:30 chrisp Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = install.xml
TARGET = install.php install-fast.php install-first.php \
	 install-up02.php install-up01.php
DESTDIR = doc/bundled

include $(basedir)/Makefile.common

# eof
