# $Id: Makefile,v 1.1 2001/07/06 20:01:53 chrisp Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = install.xml
TARGET = install.php install-first.php install-up02.php install-up01.php

include $(basedir)/Makefile.common

# eof
