# $Id: Makefile,v 1.5 2011/10/25 01:31:57 fingolfin Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = multilingual.xml
TARGET = index.php intro.php files.php procedure.php resources.php appendix.php
WANT_HTML = 1
DESTDIR = doc/multilingual

LANGUAGES_AVAILABLE = en fr zh
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.common

# eof
