# $Id: Makefile,v 1.8 2019/01/19 11:22:33 nieder Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = multilingual
TARGET = \
	index.php \
	intro.php \
	files.php \
	procedure.php \
	resources.php \
	appendix.php

WANT_HTML = 1
DESTDIR = doc/multilingual

LANGUAGES_AVAILABLE = en de fr zh
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.common

# eof
