# $Id: Makefile,v 1.3 2001/07/08 12:30:44 chrisp Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = usage.xml
TARGET = usage.php
DESTDIR = fink

include $(basedir)/Makefile.common

# eof
