# $Id: Makefile,v 1.10 2004/07/15 01:27:28 alexkhansen Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = uguide.xml
TARGET = index.php intro.php install.php upgrade.php packages.php conf.php usage.php
WANT_HTML = 1
DESTDIR = doc/users-guide

LANGUAGES = en ja zh fr es
include $(basedir)/Makefile.i18n.common

# eof
