# $Id: Makefile,v 1.15 2011/10/25 01:31:58 fingolfin Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = uguide.xml
TARGET = index.php intro.php install.php upgrade.php packages.php conf.php usage.php
WANT_HTML = 1
DESTDIR = doc/users-guide

LANGUAGES_AVAILABLE = en ja zh fr es de ru pt
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.common

# eof
