# $Id: Makefile,v 1.3 2001/10/28 08:18:26 chrisp Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = uguide.xml
TARGET = index.php intro.php install.php upgrade.php packages.php
WANT_HTML = 1
DESTDIR = doc/users-guide

include $(basedir)/Makefile.common

# eof
