<?
/* header.inc */


// directory index settings
$headrowcolor = "#cccccc";
$rowcolor1 = "#ffffff";
$rowcolor2 = "#eeeeee";


// Fink website stuff
$fsroot = $binbase."../";
$root = $relbase."../";
include $fsroot."hostlogo.inc";

$title = "Fink Archive Browser";

$linkroot = "http://www.finkproject.org/";
include $fsroot."download/nav.inc";
include $fsroot."header.inc";


// print a title
?>

<h1>The Fink Archive</h1>

