<?php

$sections = array(
	'base'            => 'Core packages',
	'crypto'          => 'Cryptographic software (subject to national regulations)',
	'database'        => 'SQL and other database software',
	'devel'           => 'Software for software development',
	'editors'         => 'Text editors',
	'games'           => 'Games and other fun stuff',
	'gnome'           => 'The GNOME desktop environment (version 2.26)',
	'graphics'        => 'Graphics applications and libraries',
	'kde'             => 'K Desktop Environment (version 3.5.10 and 4.2.4)',
	'kde/po'          => 'Translations for the K Desktop Environment (version 3.5.10 and 4.2.4)',
	'languages'       => 'Programming languages (compilers, interpreters)',
	'libs'            => 'General purpose libraries',
	'libs/ghc'        => 'Glasgow Haskell Compiler libraries',
	'libs/perlmods'   => 'Perl libraries',
	'libs/pythonmods' => 'Python libraries',
	'libs/rubymods'   => 'Ruby libraries',
	'net'             => 'Network-related applications and libraries',
	'sci'             => 'Scientific applications',
	'shells'          => 'Shells (command line interpreters)',
	'sound'           => 'Audio software',
	'text'            => 'Text-processing software',
	'utils'           => 'Utilities that do not fit elsewhere',
	'web'             => 'Web-related software',
	'x11'             => 'General X11 packages - toolkits and utilities',
	'x11-system'      => 'X Window System core packages',
	'x11-wm'          => 'Window managers for the X Window System',
);

?>
