<?php
/* $Id: nav.ru.inc,v 1.3 2019/01/19 10:11:12 nieder Exp $ */

$section = "Документация";
$navbox = array(
  "doc/index.php?phpLang=ru", "Список документов",
  "doc/users-guide/index.php?phpLang=ru", "Руководство пользователя",
  "doc/advanced/index.php?phpLang=en", "Advanced",
  "doc/x11/index.php?phpLang=ru", "Выполнение X11",
  "doc/install/index.php?phpLang=ru", "Инсталляция",
  "doc/usage/index.php?phpLang=ru", "Использование",
  "doc/readme.php?phpLang=ru", "ReadMe",
  "doc/gitaccess/index.php?phpLang=ru", "Доступ к Git",
  "doc/security/index.php?phpLang=ru", "Безопасность",
  "doc/porting/index.php?phpLang=ru", "Перенос (портинг)",
  "doc/quick-start-pkg/index.php?phpLang=ru", "Руководство по пакетированию",
  "doc/packaging/index.php?phpLang=ru", "Пакетирование",
  "doc/multilingual/index.php?phpLang=ru", "Интернационализация",
  "doc/netiquette/index.php?phpLang=ru", "Сетевой этикет"
);

?>
