<?
/* $Id: nav.fr.inc,v 1.4 2004/03/24 18:15:00 dmrrsn Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php", "Documentation",
  "doc/users-guide/index.php", "Guide utilisateur",
  "doc/x11/index.php", "Utilisation de X11",
  "doc/bundled/install.php", "Installation",
  "doc/bundled/usage.php", "Utilisation",
  "doc/readme.php", "ReadMe",
  "doc/cvsaccess/index.php", "Accès CVS",
  "doc/porting/index.php", "Portage",
  "doc/packaging/index.php", "Construction de paquets",
  "doc/multilingual/index.php", "Internationalisation"
);

?>
