<?
/* $Id: nav.ja.inc,v 1.10 2004/11/15 11:29:34 babayoshihiko Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=ja", "文書一覧",
  "doc/users-guide/index.php?phpLang=ja", "ユーザーガイド",
  "doc/x11/index.php?phpLang=ja", "X11 を使う",
  "doc/bundled/install.php?phpLang=ja", "インストール",
  "doc/bundled/usage.php?phpLang=ja", "使用方法",
  "doc/readme.php?phpLang=ja", "ReadMe",
  "doc/cvsaccess/index.php?phpLang=ja", "CVS アクセス",
  "doc/security/index.php?phpLang=ja", "セキュリティー",
  "doc/porting/index.php?phpLang=ja", "移植",
  "doc/quick-start-pkg/index.php?phpLang=ja", "パッケージ化チュートリアル",
  "doc/packaging/index.php?phpLang=ja", "パッケージ化",
  "doc/multilingual/index.php?phpLang=ja", "国際化",
  "doc/netiquette/index.php?phpLang=ja", "ネチケット"
);

?>
