<?
/* $Id: nav.zh.inc,v 1.3 2004/03/24 18:15:00 dmrrsn Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php", "文档清单",
  "doc/users-guide/index.php", "用户指南",
  "doc/x11/index.php", "运行 X11",
  "doc/bundled/install.php", "安装",
  "doc/bundled/usage.php", "使用",
  "doc/readme.php", "自述",
  "doc/cvsaccess/index.php", "CVS 访问",
  "doc/porting/index.php", "移植",
  "doc/packaging/index.php", "打包",
  "doc/multilingual/index.php", "国际化"
);

?>
