<?
/* $Id: nav.ja.inc,v 1.4 2004/03/15 14:57:17 babayoshihiko Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php", "ドキュメント一覧",
  "doc/users-guide/index.php", "利用ガイド",
  "doc/x11/index.php", "X11 を使う",
  "doc/bundled/install.php", "インストール",
  "doc/bundled/usage.php", "使用方法",
  "doc/bundled/readme.php", "ReadMe",
  "doc/cvsaccess/index.php", "CVS アクセス",
  "doc/porting/index.php", "ポート",
  "doc/packaging/index.php", "パッケージ化",
  "doc/multilingual/index.php", "国際化"
);

?>
