<?
/* $Id: nav.fr.inc,v 1.1 2004/03/07 07:25:10 michga Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php", "Documentation",
  "doc/users-guide/index.php", "Guide utilisateur",
  "doc/x11/index.php", " Utilisation de X11",
  "doc/bundled/install.php", "Installation",
  "doc/bundled/usage.php", "Utilisation",
  "doc/bundled/readme.php", "ReadMe",
  "doc/cvsaccess/index.php", "Accès CVS",
  "doc/porting/index.php", "Portage",
  "doc/packaging/index.php", "Construction de paquets"
);

?>
