<?
/* $Id: nav.es.inc,v 1.2 2005/06/14 18:36:11 dmrrsn Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=es", "Lista de Documentos",
  "doc/users-guide/index.php?phpLang=es", "Guía del Usuario",
  "doc/x11/index.php?phpLang=es", "Ejecutando X11",
  "doc/bundled/install.php?phpLang=es", "Instalación",
  "doc/bundled/usage.php?phpLang=es", "Uso",
  "doc/readme.php?phpLang=es", "Leeme",
  "doc/cvsaccess/index.php?phpLang=es", "Acceso al CVS",
  "doc/security/index.php?phpLang=es", "Seguridad",
  "doc/porting/index.php?phpLang=es", "Puertos",
  "doc/quick-start-pkg/index.php?phpLang=es", "Tutorial de Empaquetamiento",
  "doc/packaging/index.php?phpLang=es", "Manual de Empaquetamiento",
  "doc/multilingual/index.php?phpLang=es", "Internationalización",
  "doc/netiquette/index.php?phpLang=es", "Netiquette"
);

?>
