<?
/* $Id: nav.inc,v 1.8 2001/09/30 14:57:23 chrisp Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php", "Document List",
  "doc/bundled/readme.php", "ReadMe",
  "doc/bundled/install.php", "Installation",
  "doc/bundled/usage.php", "Usage",
  "doc/users-guide/index.php", "(User's Guide)",
  "doc/x11/index.php", "X11 Explained",
  "doc/cvsaccess/index.php", "CVS Access",
  "doc/porting/index.php", "Porting",
  "doc/packaging/index.php", "Packaging"
);

?>
