<?php
/* $Id: nav.de.inc,v 1.7 2019/01/19 10:11:12 nieder Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=de", "Übersicht",
  "doc/users-guide/index.php?phpLang=de", "Nutzerhandbuch",
  "doc/advanced/index.php?phpLang=de", "Für Fortgeschrittene",
  "doc/x11/index.php?phpLang=de", "Nutzung von X11",
  "doc/install/index.php?phpLang=de", "Installation",
  "doc/usage/index.php?phpLang=de", "Nutzung",
  "doc/readme.php?phpLang=de", "Lies-Mich",
  "doc/gitaccess/index.php?phpLang=de", "Git Zugang",
  "doc/security/index.php?phpLang=de", "Sicherheit",
  "doc/porting/index.php?phpLang=de", "Portierung",
  "doc/quick-start-pkg/index.php?phpLang=de", "Packaging Tutorial",
  "doc/packaging/index.php?phpLang=de", "Packaging Handbuch",
  "doc/multilingual/index.php?phpLang=de", "Internationalisierung",
  "doc/netiquette/index.php?phpLang=de", "Netiquette"
);

?>
