<?
/* $Id: nav.inc,v 1.10 2001/11/04 19:15:12 chrisp Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php", "Document List",
  "doc/users-guide/index.php", "User's Guide",
  "doc/x11/index.php", "Running X11",
  "doc/bundled/install.php", "Installation",
  "doc/bundled/usage.php", "Usage",
  "doc/bundled/readme.php", "ReadMe",
  "doc/cvsaccess/index.php", "CVS Access",
  "doc/porting/index.php", "Porting",
  "doc/packaging/index.php", "Packaging"
);

?>
