<?php
/* $Id: nav.pt.inc,v 1.7 2019/01/19 10:11:12 nieder Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=pt", "Lista de documentos",
  "doc/users-guide/index.php?phpLang=pt", "Guia do usuário",
  "doc/advanced/index.php?phpLang=pt", "Avançado",
  "doc/x11/index.php?phpLang=pt", "Executando o X11",
  "doc/install/index.php?phpLang=en", "Installation",
  "doc/usage/index.php?phpLang=en", "Usage",
  "doc/readme.php?phpLang=pt", "LeiaMe",
  "doc/gitaccess/index.php?phpLang=pt", "Acesso via Git",
  "doc/security/index.php?phpLang=pt", "Segurança",
  "doc/porting/index.php?phpLang=en", "Porting",
  "doc/quick-start-pkg/index.php?phpLang=en", "Packaging Tutorial",
  "doc/packaging/index.php?phpLang=en", "Packaging Manual",
  "doc/multilingual/index.php?phpLang=en", "Internationalization",
  "doc/netiquette/index.php?phpLang=en", "Netiquette"
);

?>
