<?php
/* $Id: nav.zh.inc,v 1.8 2014/10/23 22:05:37 thesin Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=zh", "文档清单",
  "doc/users-guide/index.php?phpLang=zh", "用户指南",
  "doc/x11/index.php?phpLang=zh", "运行 X11",
  "doc/bundled/install.php?phpLang=zh", "安装",
  "doc/bundled/usage.php?phpLang=zh", "使用",
  "doc/readme.php?phpLang=zh", "自述",
  "doc/cvsaccess/index.php?phpLang=zh", "CVS 访问",
  "doc/security/index.php?phpLang=zh", "网络安全",
  "doc/porting/index.php?phpLang=zh", "移植",
  "doc/quick-start-pkg/index.php?phpLang=zh", "Packaging Tutorial",
  "doc/packaging/index.php?phpLang=zh", "打包",
  "doc/multilingual/index.php?phpLang=zh", "国际化",
  "doc/netiquette/index.php?phpLang=zh", "网络使用规则"
);

?>
