<?php
/* $Id: nav.en.inc,v 1.11 2014/10/23 22:05:37 thesin Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=en", "Document List",
  "doc/users-guide/index.php?phpLang=en", "User's Guide",
  "doc/advanced/index.php?phpLang=en", "Advanced",
  "doc/x11/index.php?phpLang=en", "Running X11",
  "doc/install/index.php?phpLang=en", "Installation",
  "doc/usage/index.php?phpLang=en", "Usage",
  "doc/readme.php?phpLang=en", "ReadMe",
  "doc/cvsaccess/index.php?phpLang=en", "CVS Access",
  "doc/security/index.php?phpLang=en", "Security",
  "doc/porting/index.php?phpLang=en", "Porting",
  "doc/quick-start-pkg/index.php?phpLang=en", "Packaging Tutorial",
  "doc/packaging/index.php?phpLang=en", "Packaging Manual",
  "doc/multilingual/index.php?phpLang=en", "Internationalization",
  "doc/netiquette/index.php?phpLang=en", "Netiquette"
);

?>
