<?
/* $Id: nav.inc,v 1.7 2001/08/01 13:37:24 chrisp Exp $ */

$navbox = array(
  "doc/index.php", "Documentation",
  "doc/bundled/readme.php", "ReadMe",
  "doc/bundled/install.php", "Installation",
  "doc/bundled/usage.php", "Usage",
  "doc/x11/index.php", "X11 Explained",
  "doc/cvsaccess/index.php", "CVS Access",
  "doc/porting/index.php", "Porting",
  "doc/packaging/index.php", "Packaging"
);

?>
