<?
/* $Id: nav.fr.inc,v 1.7 2004/07/10 18:02:47 michga Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=fr", "Documentation",
  "doc/users-guide/index.php?phpLang=fr", "Guide utilisateur",
  "doc/x11/index.php?phpLang=fr", "Utilisation de X11",
  "doc/bundled/install.php?phpLang=fr", "Installation",
  "doc/bundled/usage.php?phpLang=fr", "Utilisation",
  "doc/readme.php?phpLang=fr", "ReadMe",
  "doc/cvsaccess/index.php?phpLang=fr", "Accès CVS",
  "doc/security/index.php?phpLang=fr", "Sécurité",
  "doc/porting/index.php?phpLang=fr", "Portage",
  "doc/packaging/index.php?phpLang=fr", "Construction de paquets",
  "doc/multilingual/index.php?phpLang=fr", "Internationalisation",
  "doc/netiquette/index.php?phpLang=fr", "Étiquette net"
);

?>
