<?
/* $Id: nav.ja.inc,v 1.9 2004/07/10 14:30:47 babayoshihiko Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=ja", "文書一覧",
  "doc/users-guide/index.php?phpLang=ja", "利用ガイド",
  "doc/x11/index.php?phpLang=ja", "X11 を使う",
  "doc/bundled/install.php?phpLang=ja", "インストール",
  "doc/bundled/usage.php?phpLang=ja", "使用方法",
  "doc/readme.php?phpLang=ja", "ReadMe",
  "doc/cvsaccess/index.php?phpLang=ja", "CVS アクセス",
  "doc/security/index.php?phpLang=en", "セキュリティー",
  "doc/porting/index.php?phpLang=ja", "ポート",
  "doc/packaging/index.php?phpLang=ja", "パッケージ化",
  "doc/multilingual/index.php?phpLang=ja", "国際化",
  "doc/netiquette/index.php?phpLang=ja", "ネチケット"
);

?>
