<?php
/* $Id: nav.es.inc,v 1.4 2019/01/19 10:11:12 nieder Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=es", "Lista de Documentos",
  "doc/users-guide/index.php?phpLang=es", "Guía del Usuario",
  "doc/advanced/index.php?phpLang=en", "Advanced",
  "doc/x11/index.php?phpLang=es", "Ejecutando X11",
  "doc/install/index.php?phpLang=es", "Instalación",
  "doc/usage/index.php?phpLang=es", "Uso",
  "doc/readme.php?phpLang=es", "Leeme",
  "doc/gitaccess/index.php?phpLang=es", "Acceso al Git",
  "doc/security/index.php?phpLang=es", "Seguridad",
  "doc/porting/index.php?phpLang=es", "Puertos",
  "doc/quick-start-pkg/index.php?phpLang=es", "Tutorial de Empaquetamiento",
  "doc/packaging/index.php?phpLang=es", "Manual de Empaquetamiento",
  "doc/multilingual/index.php?phpLang=es", "Internationalización",
  "doc/netiquette/index.php?phpLang=es", "Netiquette"
);

?>
