<?php
/* $Id: nav.de.inc,v 1.5 2015/02/23 17:56:58 k-m_schindler Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=de", "Ãœbersicht",
  "doc/users-guide/index.php?phpLang=de", "Nutzerhandbuch",
  "doc/advanced/index.php?phpLang=de", "FŸr Fortgeschrittene",
  "doc/x11/index.php?phpLang=de", "Nutzung von X11",
  "doc/bundled/install.php?phpLang=de", "Installation",
  "doc/bundled/usage.php?phpLang=de", "Nutzung",
  "doc/readme.php?phpLang=de", "Lies-Mich",
  "doc/cvsaccess/index.php?phpLang=de", "CVS Zugang",
  "doc/security/index.php?phpLang=de", "Sicherheit",
  "doc/porting/index.php?phpLang=de", "Portierung",
  "doc/quick-start-pkg/index.php?phpLang=de", "Packaging Tutorial",
  "doc/packaging/index.php?phpLang=de", "Packaging Handbuch",
  "doc/multilingual/index.php?phpLang=de", "Internationalisierung",
  "doc/netiquette/index.php?phpLang=de", "Netiquette"
);

?>
