<?
/* $Id: nav.ru.inc,v 1.1 2005/01/01 05:17:00 horsager Exp $ */

$section = "Документация";
$navbox = array(
  "doc/index.php?phpLang=ru", "Список документов",
  "doc/users-guide/index.php?phpLang=ru", "Руководство пользователя",
  "doc/x11/index.php?phpLang=ru", "Выполнение X11",
  "doc/bundled/install.php?phpLang=ru", "Инсталляция",
  "doc/bundled/usage.php?phpLang=ru", "Использование",
  "doc/readme.php?phpLang=ru", "ReadMe",
  "doc/cvsaccess/index.php?phpLang=ru", "Доступ к CVS",
  "doc/security/index.php?phpLang=ru", "Безопасность",
  "doc/porting/index.php?phpLang=ru", "Перенос (портинг)",
  "doc/quick-start-pkg/index.php?phpLang=ru", "Руководство по пакетированию",
  "doc/packaging/index.php?phpLang=ru", "Пакетирование",
  "doc/multilingual/index.php?phpLang=ru", "Интернационализация",
  "doc/netiquette/index.php?phpLang=ru", "Сетевой этикет"
);

?>
