<?
/* $Id: nav.en.inc,v 1.4 2004/03/24 18:29:08 dmrrsn Exp $ */

$section = "documentation";
$navbox = array(
  "doc/index.php?phpLang=en", "Document List",
  "doc/users-guide/index.php?phpLang=en", "User's Guide",
  "doc/x11/index.php?phpLang=en", "Running X11",
  "doc/bundled/install.php?phpLang=en", "Installation",
  "doc/bundled/usage.php?phpLang=en", "Usage",
  "doc/readme.php?phpLang=en", "ReadMe",
  "doc/cvsaccess/index.php?phpLang=en", "CVS Access",
  "doc/porting/index.php?phpLang=en", "Porting",
  "doc/packaging/index.php?phpLang=en", "Packaging",
  "doc/multilingual/index.php?phpLang=en", "Internationalization"
);

?>
