# $Id: Makefile,v 1.15 2019/01/19 11:22:33 nieder Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = porting
TARGET = \
	index.php \
	basics.php \
	shared.php \
	libtool.php \
	preparing-10.2.php \
	preparing-10.3.php \
	preparing-10.4.php

WANT_HTML = 1
DESTDIR = doc/porting

LANGUAGES_AVAILABLE = en de fr ja zh
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.common

# eof
