# $Id: Makefile,v 1.8 2004/10/20 11:11:24 dmacks Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = porting.xml
TARGET = index.php basics.php shared.php libtool.php preparing.php
WANT_HTML = 1
DESTDIR = doc/porting

LANGUAGES_AVAILABLE = en fr zh
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.i18n.common

# eof
