# $Id: Makefile,v 1.12 2011/10/25 01:31:58 fingolfin Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = porting.xml
TARGET = index.php basics.php shared.php libtool.php preparing-10.2.php preparing-10.3.php preparing-10.4.php
WANT_HTML = 1
DESTDIR = doc/porting

LANGUAGES_AVAILABLE = en fr ja zh
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.common

# eof
