<?
/* $Id: header.inc,v 1.3 2001/08/01 13:37:24 chrisp Exp $ */

$navbox = array(
  "doc/packaging/index.php", "Contents",
  "doc/packaging/intro.php", "Introduction",
  "doc/packaging/format.php", "File Format",
  "doc/packaging/policy.php", "Policy",
  "doc/packaging/fslayout.php", "FS Layout",
  "doc/packaging/reference.php", "Reference"
);

$fsroot = $root = "../../";
include $fsroot."header.inc";
?>
