# $Id: Makefile,v 1.3 2001/10/26 20:57:48 chrisp Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = x11.xml
TARGET = index.php intro.php history.php \
	 inst-xfree86.php run-xfree86.php xtools.php other.php \
	 trouble.php tips.php
DESTDIR = doc/x11

include $(basedir)/Makefile.common

# eof
