# $Id: Makefile,v 1.8 2004/04/04 02:30:21 michga Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = x11.xml
TARGET = index.php intro.php history.php \
	 inst-xfree86.php run-xfree86.php xtools.php other.php \
	 trouble.php tips.php
WANT_HTML = 1
DESTDIR = doc/x11

LANGUAGES = en fr ja zh
include $(basedir)/Makefile.i18n.common

# eof
