# $Id: Makefile,v 1.2 2004/03/31 00:38:58 michga Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = netiquette.xml
TARGET = index.php before-post.php first-post.php reply.php unsubscribe.php 
WANT_HTML = 1
DESTDIR = doc/netiquette

LANGUAGES = en fr
include $(basedir)/Makefile.i18n.common

# eof
