# $Id: Makefile,v 1.8 2011/10/25 01:31:57 fingolfin Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = netiquette.xml
TARGET = index.php before-post.php first-post.php reply.php unsubscribe.php 
WANT_HTML = 1
DESTDIR = doc/netiquette

LANGUAGES_AVAILABLE = en es fr zh ja ru
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.common

# eof
