<?
/* $Id: header.inc,v 1.6 2004/02/19 07:53:02 dmalloc Exp $ */

$section = "mailing-lists";
$navbox = array(
  "lists/index.php", "Overview",
  "lists/fink-announce.php", "fink-announce",
  "lists/fink-i18n.php", "fink-i18n",
  "lists/fink-beginners.php", "fink-beginners",
  "lists/fink-users.php", "fink-users",
  "lists/fink-devel.php", "fink-devel",
  "lists/fink-core.php", "fink-core",
  "lists/fink-gnome-core.php", "fink-gnome-core",
  "lists/fink-commits.php", "fink-commits",
  "lists/fink-tracker.php", "fink-tracker"
);

$fsroot = $root = "../";
include $fsroot."header.inc";
?>
