<?
/* $Id: header.inc,v 1.4 2001/12/06 17:21:20 fingolfin Exp $ */

$section = "mailing-lists";
$navbox = array(
  "lists/index.php", "Overview",
  "lists/fink-announce.php", "fink-announce",
  "lists/fink-beginners.php", "fink-beginners",
  "lists/fink-users.php", "fink-users",
  "lists/fink-devel.php", "fink-devel",
  "lists/fink-commits.php", "fink-commits"
);

$fsroot = $root = "../";
include $fsroot."header.inc";
?>
