# $Id: Makefile,v 1.1 2004/07/15 16:16:11 michga Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = quick-start-pkg.xml
# The second example is not ready yet...
#TARGET = index.php howtostart.php example.php example2.php
TARGET = index.php howtostart.php example.php
WANT_HTML = 1
DESTDIR = doc/quick-start-pkg

LANGUAGES = en
include $(basedir)/Makefile.i18n.common

# eof
