<?
/* $Id: header.inc,v 1.2 2001/08/01 13:37:24 chrisp Exp $ */

$navbox = array(
  "doc/x11/index.php", "Contents",
  "doc/x11/intro.php", "Introduction",
  "doc/x11/history.php", "History",
  "doc/x11/inst-xfree86.php", "XFree86 (1)",
  "doc/x11/run-xfree86.php", "XFree86 (2)",
  "doc/x11/xtools.php", "Xtools",
  "doc/x11/other.php", "Other Stuff",
  "doc/x11/trouble.php", "Problems?"
);

$fsroot = $root = "../../";
include $fsroot."header.inc";
?>
