<?
/* $Id: header.inc,v 1.3 2001/09/30 14:57:24 chrisp Exp $ */

$section = "documentation";
$parents = array("doc/index.php", "Document List");
$navbox = array(
  "doc/x11/index.php", "Contents",
  "doc/x11/intro.php", "Introduction",
  "doc/x11/history.php", "History",
  "doc/x11/inst-xfree86.php", "XFree86 (1)",
  "doc/x11/run-xfree86.php", "XFree86 (2)",
  "doc/x11/xtools.php", "Xtools",
  "doc/x11/other.php", "Other Stuff",
  "doc/x11/trouble.php", "Problems?"
);

$fsroot = $root = "../../";
include $fsroot."header.inc";
?>
