<?
/* $Id: nav.inc,v 1.2 2001/07/23 11:46:31 chrisp Exp $ */

$customnav = array(
  "doc/x11/index.php", "Contents", 0,
  "doc/x11/intro.php", "Introduction", 0,
  "doc/x11/history.php", "History", 0,
  "doc/x11/inst-xfree86.php", "XFree86 (1)", 0,
  "doc/x11/run-xfree86.php", "XFree86 (2)", 0,
  "doc/x11/xtools.php", "Xtools", 0,
  "doc/x11/other.php", "Other Stuff", 0,
  "doc/x11/trouble.php", "Troubleshooting", 0
);

?>
