# $Id: Makefile,v 1.1 2019/01/25 10:11:22 nieder Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = git
TARGET = index.php
WANT_HTML = 1
DESTDIR = doc/gitaccess

LANGUAGES_AVAILABLE = en
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.common

# eof
