# $Id: Makefile,v 1.3 2004/07/08 15:44:41 dmalloc Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = sec-policy.xml
TARGET = index.php respo.php severity.php sources.php updating.php notification.php 
WANT_HTML = 1
DESTDIR = doc/security

LANGUAGES = en fr zh
include $(basedir)/Makefile.i18n.common

# eof
