# $Id: Makefile,v 1.5 2004/10/20 11:11:25 dmacks Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = sec-policy.xml
TARGET = index.php respo.php severity.php sources.php updating.php notification.php 
WANT_HTML = 1
DESTDIR = doc/security

LANGUAGES_AVAILABLE = en fr zh ja
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.i18n.common

# eof
