# $Id: Makefile,v 1.1 2004/06/15 18:19:01 dmalloc Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = sec-policy.xml
TARGET = index.php respo.php severity.php sources.php updating.php 
WANT_HTML = 1
DESTDIR = doc/security

LANGUAGES = en
include $(basedir)/Makefile.i18n.common

# eof
