# $Id: Makefile,v 1.3 2006/01/03 19:30:32 dmacks Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = advanced.xml
TARGET = index.php bindist.php
WANT_HTML = 1
DESTDIR = doc/advanced

LANGUAGES_AVAILABLE = en fr ja
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.i18n.common

# eof
