# $Id: Makefile,v 1.2 2005/03/02 05:18:58 michga Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = advanced.xml
TARGET = index.php bindist.php
WANT_HTML = 1
DESTDIR = doc/advanced

LANGUAGES_AVAILABLE = en fr
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.i18n.common

# eof
