# $Id: Makefile,v 1.6 2011/10/25 01:55:44 fingolfin Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = advanced
TARGET = index.php bindist.php
WANT_HTML = 1
DESTDIR = doc/advanced

LANGUAGES_AVAILABLE = en fr ja pt
LANGUAGES = $(LANGUAGES_AVAILABLE)
include $(basedir)/Makefile.common

# eof
