<?
/* $Id: nav.de.inc,v 1.5 2006/06/28 16:00:04 dmrrsn Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=de", "Quick Start",
  "download/overview.php?phpLang=de", "Übersicht",
  "download/bindist.php?phpLang=de", "Binär Version",
  "download/srcdist.php?phpLang=de", "Quelltext Version",
  "download/upgrade.php?phpLang=de", "Upgrade Matrix",
  "download/10.1-upgrade.php?phpLang=de", "10.1 Upgrades",
  "download/10.2-upgrade.php?phpLang=de", "10.2 Upgrades",
  "download/10.3-upgrade.php?phpLang=de", "10.3 Upgrades",
  "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  "http://bindist.finkmirrors.net/bindist/dists/", "Archiv Browser"
);

?>
