<?php
/* $Id: nav.fr.inc,v 1.10 2014/10/23 22:32:37 thesin Exp $ */

$section = "download";
$navbox = array(
  $hostlink . "download/index.php?phpLang=fr", "Téléchargement rapide",
  $hostlink . "download/overview.php?phpLang=fr", "Généralités",
  $hostlink . "download/bindist.php?phpLang=fr", "Version binaire",
  $hostlink . "download/srcdist.php?phpLang=fr", "Version source",
  $hostlink . "download/upgrade.php?phpLang=fr", "Tableau mises à jour",
  $hostlink . "download/10.6-upgrade.php?phpLang=fr", "Mise à niveau 10.6",
  $hostlink . "download/10.7-upgrade.php?phpLang=fr", "Mise à niveau 10.7",
  $hostlink . "download/sources_for_binaries.php?phpLang=fr", "Sources des binaires",
  "http://bindist.finkmirrors.net/", "Répertoires archives"
);

?>
