<?
/* $Id: nav.inc,v 1.2 2001/09/30 14:57:24 chrisp Exp $ */

$section = "download";
$navbox = array(
  "download/index.php", "Quick Start",
  "download/overview.php", "Overview",
  "download/bindist.php", "Binary Release",
  "download/srcdist.php", "Source Release",
  "download/upgrade.php", "Upgrade Matrix",
  "download/puma-kit.php", "10.1 Upgrade Kit",
  "bindist/.*", "Archive Browser"
);

?>
