<?
/* $Id: nav.pt.inc,v 1.4 2009/03/30 00:18:08 monipol Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=pt", "Guia rápido",
  "download/overview.php?phpLang=pt", "Visão geral",
  "download/bindist.php?phpLang=pt", "Versão binária",
  "download/srcdist.php?phpLang=pt", "Versão de código fonte",
  "download/upgrade.php?phpLang=pt", "Matriz de atualizações",
  "download/10.1-upgrade.php?phpLang=pt", "Atualização para 10.1",
  "download/10.2-upgrade.php?phpLang=pt", "Atualização para 10.2",
  "download/10.3-upgrade.php?phpLang=pt", "Atualização para 10.3",
  "download/sources_for_binaries.php?phpLang=pt", "Fontes para os binários",
  "http://bindist.finkmirrors.net/bindist/dists/", "Archive browser"
);

?>
