<?php
/* $Id: nav.it.inc,v 1.8 2014/11/30 18:43:47 alexkhansen Exp $ */

$section = "download";
$navbox = array(
  $hostlink . "download/index.php?phpLang=en", "Avvio Rapido",
  $hostlink . "download/overview.php?phpLang=en", "Panoramica",
  $hostlink . "download/bindist.php?phpLang=en", "Binary Release",
  $hostlink . "download/srcdist.php?phpLang=en", "Source Release",
  $hostlink . "download/upgrade.php?phpLang=en", "Aggiornamento Matrice",
  $hostlink . "download/10.6-upgrade.php?phpLang=en", "Aggiornamento 10.6",
  $hostlink . "download/10.7-upgrade.php?phpLang=en", "Aggiornamento 10.7",
  $hostlink . "download/10.8-upgrade.php?phpLang=en", "Aggiornamento 10.8",
  $hostlink . "download/10.9-upgrade.php?phpLang=en", "Aggiornamento 10.9",
  $hostlink . "download/10.10-upgrade.php?phpLang=en", "Aggiornamento 10.10",
  $hostlink . "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  "http://bindist.finkmirrors.net/", "Browser archivio"
);

?>
