<?
/* $Id: nav.de.inc,v 1.6 2011/10/26 11:23:15 fingolfin Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=de", "Quick Start",
  "download/overview.php?phpLang=de", "Übersicht",
  "download/bindist.php?phpLang=de", "Binär Version",
  "download/srcdist.php?phpLang=de", "Quelltext Version",
  "download/upgrade.php?phpLang=de", "Upgrade Matrix",
  "download/10.6-upgrade.php?phpLang=de", "10.6 Upgrades",
  "download/10.7-upgrade.php?phpLang=de", "10.7 Upgrades",
  "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  "http://bindist.finkmirrors.net/bindist/dists/", "Archiv Browser"
);

?>
