<?
/* $Id: nav.ja.inc,v 1.12 2014/02/16 19:36:39 thesin Exp $ */

$section = "download";
$navbox = array(
  $hostlink . "download/index.php?phpLang=ja", "はじめの一歩",
  $hostlink . "download/overview.php?phpLang=ja", "概要",
  $hostlink . "download/bindist.php?phpLang=ja", "バイナリリリース",
  $hostlink . "download/srcdist.php?phpLang=ja", "ソースリリース",
  $hostlink . "download/upgrade.php?phpLang=ja", "アップグレード表",
  $hostlink . "download/10.6-upgrade.php?phpLang=ja", "10.6 アップグレード",
  $hostlink . "download/10.7-upgrade.php?phpLang=ja", "10.7 アップグレード",
  $hostlink . "download/sources_for_binaries.php?phpLang=ja", "バイナリ用ソース",
  "http://bindist.finkmirrors.net/", "Archive Browser"
);

?>
