<?
/* $Id: nav.zh.inc,v 1.4 2006/06/28 16:00:04 dmrrsn Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=zh", "快速上手",
  "download/overview.php?phpLang=zh", "下载概述",
  "download/bindist.php?phpLang=zh", "二进制版本",
  "download/srcdist.php?phpLang=zh", "源代码版本",
  "download/upgrade.php?phpLang=zh", "升级矩阵",
  "download/10.1-upgrade.php?phpLang=zh", "10.1 升级",
  "download/10.2-upgrade.php?phpLang=zh", "10.2 升级",
  "download/10.3-upgrade.php?phpLang=zh", "10.3 升级",
  "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  "http://bindist.finkmirrors.net/bindist/dists/", "旧文档"
);

?>
