<?
/* $Id: nav.ja.inc,v 1.9 2011/10/26 11:23:15 fingolfin Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=ja", "はじめの一歩",
  "download/overview.php?phpLang=ja", "概要",
  "download/bindist.php?phpLang=ja", "バイナリリリース",
  "download/srcdist.php?phpLang=ja", "ソースリリース",
  "download/upgrade.php?phpLang=ja", "アップグレード表",
  "download/10.6-upgrade.php?phpLang=ja", "10.6 アップグレード",
  "download/10.7-upgrade.php?phpLang=ja", "10.7 アップグレード",
  "download/sources_for_binaries.php?phpLang=ja", "バイナリ用ソース",
  "http://bindist.finkmirrors.net/bindist/dists/", "Archive Browser"
);

?>
