<?
/* $Id: nav.it.inc,v 1.4 2013/11/18 15:47:17 thesin Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=en", "Avvio Rapido",
  "download/overview.php?phpLang=en", "Panoramica",
  "download/bindist.php?phpLang=en", "Binary Release",
  "download/srcdist.php?phpLang=en", "Source Release",
  "download/upgrade.php?phpLang=en", "Aggiornamento Matrice",
  "download/10.6-upgrade.php?phpLang=en", "Aggiornamento 10.6",
  "download/10.7-upgrade.php?phpLang=en", "Aggiornamento 10.7",
  "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  "http://bindist.finkmirrors.net/dists/", "Browser archivio"
);

?>
