<?php
/* $Id: nav.zh.inc,v 1.13 2016/09/21 18:27:06 thesin Exp $ */

$section = "download";
$navbox = array(
  $hostlink . "download/index.php?phpLang=zh", "快速上手",
  $hostlink . "download/overview.php?phpLang=zh", "下载概述",
  $hostlink . "download/bindist.php?phpLang=zh", "二进制版本",
  $hostlink . "download/srcdist.php?phpLang=zh", "源代码版本",
  $hostlink . "download/upgrade.php?phpLang=zh", "升级矩阵",
  $hostlink . "download/10.6-upgrade.php?phpLang=zh", "10.6 升级",
  $hostlink . "download/10.7-upgrade.php?phpLang=zh", "10.7 升级",
  $hostlink . "download/10.8-upgrade.php?phpLang=zh", "10.8 升级",
  $hostlink . "download/10.9-upgrade.php?phpLang=zh", "10.9 升级",
  $hostlink . "download/10.10-upgrade.php?phpLang=zh", "10.10 升级",
  $hostlink . "download/10.11-upgrade.php?phpLang=zh", "10.11 升级",
  $hostlink . "download/10.12-upgrade.php?phpLang=en", "10.12 升级",
  $hostlink . "download/10.13-upgrade.php?phpLang=en", "10.13 升级",
  $hostlink . "download/10.14-upgrade.php?phpLang=en", "10.14 升级",
  $hostlink . "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  $hostlink . "download/archive.php?phpLang=en", "旧文档"
  //"http://bindist.finkmirrors.net/", "旧文档"
);

?>
