<?
/* $Id: nav.fr.inc,v 1.4 2006/06/28 16:00:04 dmrrsn Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=fr", "Téléchargement rapide",
  "download/overview.php?phpLang=fr", "Généralités",
  "download/bindist.php?phpLang=fr", "Version binaire",
  "download/srcdist.php?phpLang=fr", "Version source",
  "download/upgrade.php?phpLang=fr", "Tableau mises à jour",
  "download/10.1-upgrade.php?phpLang=fr", "Mise à niveau 10.1",
  "download/10.2-upgrade.php?phpLang=fr", "Mise à niveau 10.2",
  "download/10.3-upgrade.php?phpLang=fr", "Mise à niveau 10.3",
  "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  "http://bindist.finkmirrors.net/bindist/dists/", "Répertoires archives"
);

?>
