<?
/* $Id: nav.en.inc,v 1.5 2010/01/10 22:12:56 alexkhansen Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=en", "Quick Start",
  "download/overview.php?phpLang=en", "Overview",
  "download/bindist.php?phpLang=en", "Binary Release",
  "download/srcdist.php?phpLang=en", "Source Release",
  "download/upgrade.php?phpLang=en", "Upgrade Matrix",
  "download/10.6-upgrade.php?phpLang=en", "10.6 Upgrades",
  "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  "http://bindist.finkmirrors.net/bindist/dists/", "Archive Browser"
);

?>
