<?php
/* $Id: nav.en.inc,v 1.12 2014/10/23 22:32:37 thesin Exp $ */

$section = "download";
$navbox = array(
  $hostlink . "download/index.php?phpLang=en", "Quick Start",
  $hostlink . "download/overview.php?phpLang=en", "Overview",
  $hostlink . "download/bindist.php?phpLang=en", "Binary Release",
  $hostlink . "download/srcdist.php?phpLang=en", "Source Release",
  $hostlink . "download/upgrade.php?phpLang=en", "Upgrade Matrix",
  $hostlink . "download/10.6-upgrade.php?phpLang=en", "10.6 Upgrades",
  $hostlink . "download/10.7-upgrade.php?phpLang=en", "10.7 Upgrades",
  $hostlink . "download/10.8-upgrade.php?phpLang=en", "10.8 Upgrades",
  $hostlink . "download/10.9-upgrade.php?phpLang=en", "10.9 Upgrades",
  $hostlink . "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  "http://bindist.finkmirrors.net/", "Archive Browser"
);

?>
