<?
/* $Id: nav.zh.inc,v 1.1 2004/03/03 05:20:03 jeff_yecn Exp $ */

$section = "download";
$navbox = array(
  "download/index.php", "快速上手",
  "download/overview.php", "下载概述",
  "download/bindist.php", "二进制版本",
  "download/srcdist.php", "源代码版本",
  "download/upgrade.php", "升级矩阵",
  "download/10.1-upgrade.php", "10.1 升级",
  "download/10.2-upgrade.php", "10.2 升级",
  "download/10.3-upgrade.php", "10.3 升级",
  "bindist/.*", "旧文档"
);

?>
