<?
/* $Id: nav.inc,v 1.4 2004/02/28 18:26:16 fingolfin Exp $ */

$section = "download";
$navbox = array(
  "download/index.php", "Quick Start",
  "download/overview.php", "Overview",
  "download/bindist.php", "Binary Release",
  "download/srcdist.php", "Source Release",
  "download/upgrade.php", "Upgrade Matrix",
  "download/10.1-upgrade.php", "10.1 Upgrades",
  "download/10.2-upgrade.php", "10.2 Upgrades",
  "download/10.3-upgrade.php", "10.3 Upgrades",
  "bindist/.*", "Archive Browser"
);

?>
