<?
/* $Id: nav.pt.inc,v 1.2 2009/03/25 03:04:22 monipol Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=fr", "Guia rápido",
  "download/overview.php?phpLang=fr", "Visão geral",
  "download/bindist.php?phpLang=fr", "Versão binária",
  "download/srcdist.php?phpLang=fr", "Versão de código fonte",
  "download/upgrade.php?phpLang=fr", "Matriz de atualizações",
  "download/10.1-upgrade.php?phpLang=fr", "Atualização para 10.1",
  "download/10.2-upgrade.php?phpLang=fr", "Atualização para 10.2",
  "download/10.3-upgrade.php?phpLang=fr", "Atualização para 10.3",
  "download/sources_for_binaries.php?phpLang=fr", "Fontes para os binários",
  "http://bindist.finkmirrors.net/bindist/dists/", "Repositório"
);

?>
