<?
/* $Id: nav.ja.inc,v 1.6 2006/06/28 16:00:04 dmrrsn Exp $ */

$section = "download";
$navbox = array(
  "download/index.php?phpLang=ja", "はじめの一歩",
  "download/overview.php?phpLang=ja", "概要",
  "download/bindist.php?phpLang=ja", "バイナリリリース",
  "download/srcdist.php?phpLang=ja", "ソースリリース",
  "download/upgrade.php?phpLang=ja", "アップグレード表",
  "download/10.1-upgrade.php?phpLang=ja", "10.1 アップグレード",
  "download/10.2-upgrade.php?phpLang=ja", "10.2 アップグレード",
  "download/10.3-upgrade.php?phpLang=ja", "10.3 アップグレード",
  "download/sources_for_binaries.php?phpLang=en", "Sources for Binaries",
  "http://bindist.finkmirrors.net/bindist/dists/", "Archive Browser"
);

?>
