<?
/* $Id: nav.inc,v 1.3 2002/12/17 18:55:00 dmrrsn Exp $ */

$section = "download";
$navbox = array(
  "download/index.php", "Quick Start",
  "download/overview.php", "Overview",
  "download/bindist.php", "Binary Release",
  "download/srcdist.php", "Source Release",
  "download/upgrade.php", "Upgrade Matrix",
  "download/10.1-upgrade.php", "10.1 Upgrades",
  "download/10.2-upgrade.php", "10.2 Upgrades",
  "bindist/.*", "Archive Browser"
);

?>
